---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: arc-systems
spec:
  releaseName: arc
  chart:
    spec:
      chart: arc
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3