---
# Source: gha-runner-scale-set/templates/manager_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${flux_github_arc_runners_scale_set_name}-gha-rs-manager
  namespace: arc-runners
  labels:
    app.kubernetes.io/name: ${flux_github_arc_runners_scale_set_name}
    app.kubernetes.io/instance: ${flux_github_arc_runners_scale_set_name}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: ${flux_github_arc_runners_scale_set_name}
    actions.github.com/scale-set-namespace: arc-runners
    app.kubernetes.io/component: manager-role
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - delete
      - get
      - patch
      - update
