apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldpinger
  namespace: goldpinger
spec:
  serviceAccountName: helm-controller
  releaseName: goldpinger
  chart:
    spec:
      chart: goldpinger
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: goldpinger
        namespace: goldpinger
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    priorityClassName: node-observability
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
    serviceMonitor:
      enabled: true
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 64Mi
    tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
