apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldpinger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: goldpinger
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: goldpinger
        namespace: flux-system
  values:
    priorityClassName: cluster-monitoring
    serviceMonitor:
      enabled: true
      selector:
        release: monitoring
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 50Mi
    tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
  interval: 1m0s
  releaseName: goldpinger
  targetNamespace: goldpinger
