---
# Source: keda/templates/manager/minimal-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-minimal-cluster-role
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/instance: keda
  name: keda-operator-minimal-cluster-role
rules:
  - apiGroups:
      - keda.sh
    resources:
      - clustertriggerauthentications
      - clustertriggerauthentications/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - eventing.keda.sh
    resources:
      - cloudeventsources
      - cloudeventsources/status
      - clustercloudeventsources
      - clustercloudeventsources/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
