---
# Source: keda/templates/metrics-server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: keda-metrics-server
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/instance: keda
  annotations:
  name: keda-metrics-server
  namespace: keda
automountServiceAccountToken: true
