apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      version: 0.17.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  interval: 1m
  values:
    installCRDS: true
    priorityClassName: cluster-infrastructure
    webhook:
      priorityClassName: cluster-infrastructure
    certController:
      priorityClassName: cluster-infrastructure
