apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  serviceAccountName: helm-controller
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 0.19.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  interval: 1m
  values:
    installCRDS: true
    priorityClassName: cluster-infrastructure
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi
    webhook:
      priorityClassName: cluster-infrastructure
      resources:
        limits:
          memory: 64Mi
        requests:
          cpu: 1m
          memory: 64Mi
    certController:
      priorityClassName: cluster-infrastructure
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 1m
          memory: 128Mi
