apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: aws-lb-controller
    namespace: aws-lb-controller
rules:
  - apiGroups:
       - ""
    resourceNames:
      - "*"
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: aws-lb-controller-rolebinding
    namespace: aws-lb-controller
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: aws-lb-controller
subjects:
  - kind: ServiceAccount
    name: aws-lb-controller
    namespace: aws-lb-controller