apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-lb-controller
  namespace: aws-lb-controller
spec:
  releaseName: aws-lb-controller
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
  interval: 1m
  install:
    crds: Skip
    remediation:
      retries: 3
  values:
    serviceAccount:
      name: aws-lb-controller
      annotations:
        eks.amazonaws.com/role-arn: ${flux_aws_alb_controller_role_arn}
    region: ${flux_cluster_region}
    clusterName: ${flux_cluster_name}
    priorityClassName: cluster-infrastructure
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        memory: 64Mi
    watchNamespace: aws-lb-controller
