apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ${flux_cert_manager_acme_email}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the DNS-01 challenge provider
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector:
          dnsZones:
            - ${flux_cert_manager_domain_name}
        dns01:
          route53:
            region: us-east-1
            role: ${flux_cert_manager_iam_role_arn}
            auth:
              kubernetes:
                serviceAccountRef:
                  name: cert-manager