---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 15m
  url: https://charts.jetstack.io

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  serviceAccountName: helm-controller
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "v1.18.2"
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 15m
  values:
    installCRDs: false
    global:
      priorityClassName: cluster-infrastructure
    serviceAccount:
      name: cert-manager
    securityContext:
      fsGroup: 1001
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 256Mi
    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 64Mi
    cainjector:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 64Mi
