---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snapshot-controller-leaderelection
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: snapshot-controller-leaderelection
subjects:
  - kind: ServiceAccount
    name: snapshot-controller
