---
# Source: falco/charts/falcosidekick/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "falco-falcosidekick-test-connection"
  namespace: falco
  labels:
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/instance: falco
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: curl
      image: appropriate/curl
      command: ['curl']
      args: ["-X", "POST", 'falco-falcosidekick:2801/ping']
  restartPolicy: Never
