---
# Source: falco/charts/falcosidekick/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: falco-falcosidekick
  namespace: falco
  labels:
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/instance: falco
    app.kubernetes.io/part-of: falcosidekick
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: core
  annotations:
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
