---
# Source: falco/charts/falcosidekick/templates/rbac-ui.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: falco-falcosidekick-ui
  namespace: falco
  labels:
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/instance: falco
    app.kubernetes.io/part-of: falcosidekick
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ui
  annotations:
rules: []
