---
# Source: falco/charts/falcosidekick/templates/service-ui.yaml
apiVersion: v1
kind: Service
metadata:
  name: falco-falcosidekick-ui-redis
  namespace: falco
  labels:
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/instance: falco
    app.kubernetes.io/part-of: falcosidekick
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/instance: falco
    app.kubernetes.io/component: ui-redis
