---
# Source: falco/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: falco-metrics
  namespace: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/instance: falco
    app.kubernetes.io/managed-by: Helm
    type: "falco-metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8765
      targetPort: 8765
      protocol: TCP
      name: "metrics"
  selector:
    app.kubernetes.io/name: falco
    app.kubernetes.io/instance: falco
