---
# Source: falco/charts/k8s-metacollector/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-k8s-metacollector
  namespace: falco
  labels:
    app.kubernetes.io/name: k8s-metacollector
    app.kubernetes.io/instance: falco
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "metadata-collector"
