apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resources
  annotations:
    policies.kyverno.io/title: Require Resource Limits and Requests
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Containers must specify resource requests and limits for CPU and memory.
      This prevents resource exhaustion and ensures fair resource allocation.
      Note: This is a best practice but not part of the Pod Security Standards.
spec:
  validationFailureAction: Audit
  emitWarning: false
  background: true
  rules:
    - name: require-cpu-requests
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          CPU requests are required. All containers must specify 
          spec.containers[*].resources.requests.cpu
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
    - name: require-cpu-limits
      match:
        any:
        - resources:
            kinds:
              - Pod
      exclude:
        any:
        - resources:
            namespaces:
              - kube-system
              - kyverno
      validate:
        message: >-
          CPU limits are required. All containers must specify 
          spec.containers[*].resources.limits.cpu
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    cpu: "?*"
    - name: require-memory-requests
      match:
        any:
        - resources:
            kinds:
              - Pod
      exclude:
        any:
        - resources:
            namespaces:
              - kube-system
              - kyverno
      validate:
        message: >-
          Memory requests are required. All containers must specify 
          spec.containers[*].resources.requests.memory
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    memory: "?*"
    - name: require-memory-limits
      match:
        any:
        - resources:
            kinds:
              - Pod
      exclude:
        any:
        - resources:
            namespaces:
              - kube-system
              - kyverno
      validate:
        message: >-
          Memory limits are required. All containers must specify 
          spec.containers[*].resources.limits.memory
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
