apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resources
  annotations:
    policies.kyverno.io/title: Require Resource Limits and Requests
    policies.kyverno.io/category: Operational (Best Practices)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Containers must specify CPU requests (without limits) and memory requests/limits (equal).
      CPU limits should not be set to avoid throttling. Memory requests and limits must be equal.
      This prevents resource exhaustion and ensures fair resource allocation.
      Note: This is a best practice but not part of the Pod Security Standards.
spec:
  validationFailureAction: Audit
  emitWarning: false
  background: true
  rules:
    - name: require-cpu-requests
      match:
        any:
        - resources:
            kinds:
              - Pod
            operations:
              - CREATE
              - UPDATE
      exclude:
        any:
        - resources:
            namespaces:
              - kube-system
              - kyverno
      validate:
        message: >-
          All containers must specify spec.containers[*].resources.requests.cpu.
          Visit https://wiki.dfds.cloud/en/playbooks/kyverno#require-resource-limits-and-requests for more information.
        pattern:
          spec:
            containers:
            - resources:
                requests:
                  cpu: "?*"
    - name: deny-cpu-limits
      match:
        any:
        - resources:
            kinds:
              - Pod
            operations:
              - CREATE
              - UPDATE
      exclude:
        any:
        - resources:
            namespaces:
              - kube-system
              - kyverno
      validate:
        message: >-
          Containers must NOT set spec.containers[*].resources.limits.cpu (to avoid CPU throttling).
          Visit https://wiki.dfds.cloud/en/playbooks/kyverno#require-resource-limits-and-requests for more information.
        foreach:
        - list: "request.object.spec.containers"
          deny:
            conditions:
              any:
              - key: "{{ to_string(element.resources.limits.cpu || '') }}"
                operator: NotEquals
                value: ""
    - name: require-memory-resources
      match:
        any:
        - resources:
            kinds:
              - Pod
            operations:
              - CREATE
              - UPDATE
      exclude:
        any:
        - resources:
            namespaces:
              - kube-system
              - kyverno
      validate:
        message: >-
          All containers must specify both spec.containers[*].resources.requests.memory
          and spec.containers[*].resources.limits.memory.
          Visit https://wiki.dfds.cloud/en/playbooks/kyverno#require-resource-limits-and-requests for more information.
        pattern:
          spec:
            containers:
            - resources:
                requests:
                  memory: "?*"
                limits:
                  memory: "?*"
    - name: require-equal-memory-resources
      match:
        any:
        - resources:
            kinds:
              - Pod
            operations:
              - CREATE
              - UPDATE
      exclude:
        any:
        - resources:
            namespaces:
              - kube-system
              - kyverno
      validate:
        message: >-
          Memory requests and limits must be equal:
          spec.containers[*].resources.requests.memory must equal
          spec.containers[*].resources.limits.memory.
          Visit https://wiki.dfds.cloud/en/playbooks/kyverno#require-resource-limits-and-requests for more information.
        foreach:
        - list: "request.object.spec.containers"
          preconditions:
            all:
            - key: "{{ to_string(element.resources.requests.memory || '') }}"
              operator: NotEquals
              value: ""
            - key: "{{ to_string(element.resources.limits.memory || '') }}"
              operator: NotEquals
              value: ""
          deny:
            conditions:
              any:
              - key: "{{ to_string(element.resources.requests.memory) }}"
                operator: NotEquals
                value: "{{ to_string(element.resources.limits.memory) }}"
