apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: arc
  namespace: flux-system
spec:
  interval: 5m0s
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
