apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: keda
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kedacore.github.io/charts
  values:
    webhooks:
      replicaCount: 3
    priorityClassName: "system-cluster-critical"
