apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-cloudwatch
  labels:
    app: fluentd-cloudwatch
subjects:
- kind: ServiceAccount
  name: fluentd-cloudwatch
  namespace: fluentd
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-cloudwatch
  apiGroup: ""
