apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-cloudwatch
  namespace: fluentd
  labels:
    app: fluentd-cloudwatch
spec:
  selector:
    matchLabels:
      app: fluentd-cloudwatch
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: fluentd-cloudwatch
    spec:
      priorityClassName: cluster-monitoring
      serviceAccountName: fluentd-cloudwatch
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      terminationGracePeriodSeconds: 30
      containers:
        - name: fluentd-cloudwatch
          image: fluent/fluentd-kubernetes-daemonset:INVALID
          command:
            - sh
            - "-c"
            - sed -i "s/match \*\*/match disablethis/g" /fluentd/etc/fluent.conf && tini -- /fluentd/entrypoint.sh
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 768Mi
          env:
            - name: FLUENTD_ARGS
              value: --no-supervisor -q
            - name: AWS_REGION
              value: "eu-west-1"
            - name: RETENTION_IN_DAYS
              value: "7"
            - name: FLUENTD_SYSTEMD_CONF
              value: "disable"
            - name: FLUENT_CONTAINER_TAIL_TAG
              value: "raw.kubernetes.*"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: libsystemdir
              mountPath: /host/lib
              readOnly: true
            - name: config-volume
              mountPath: /fluentd/etc/conf.d
              readOnly: false
          livenessProbe:
            httpGet:
              path: /metrics
              port: 24231
              targetPort: 24231
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: libsystemdir
          hostPath:
            path: /usr/lib64
        - name: config-volume
          configMap:
            name: fluentd-cloudwatch
