apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluentd
resources:
  - namespace.yaml
  - clusterrole.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - daemonset.yaml
  - service.yaml