---
apiVersion: v1
kind: Service
metadata:
  labels:
    scrape-service-metrics: "true"
  name: kustomize-controller
  namespace: flux-system
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kustomize-controller
