---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: eks-version-exporter
  namespace: monitoring
spec:
  interval: 1h0m0s
  ref:
    branch: feature/add-helm-chart #master
  timeout: 60s
  url: https://github.com/dfds/eks-version-exporter
