apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
  namespace: vpa
spec:
  serviceAccountName: helm-controller
  targetNamespace: vpa
  chart:
    spec:
      chart: vertical-pod-autoscaler
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: vpa
        namespace: vpa
  interval: 1m
  install:
    crds: Skip
  values:
    admissionController:
      replicas: 3
      resources:
        limits:
          memory: 500Mi
        requests:
          cpu: 50m
          memory: 500Mi
      priorityClassName: system-cluster-critical
      certGen:
        enabled: false # cert-manager is used to generate the certs
      certManager:
        enabled: true
        createSelfSignedIssuer:
          enabled: true
        issuerRef:
          name: self-signer
          kind: Issuer
    recommender:
      replicas: 1
      resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 500Mi
      priorityClassName: system-cluster-critical
      extraArgs:
        - --humanize-memory=true
        - --memory-saver
        - --round-memory-bytes=1
    updater:
      replicas: 1
      resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 500Mi
      priorityClassName: system-cluster-critical