---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general
  annotations:
    kubernetes.io/description: "General purpose NodePool for generic workloads"
spec:
  limits:
    cpu: 32
    # memory: 60Gi
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
  template:
    labels:
      - key: "dfds.com/nodegroup-purpose"
        value: "general"
    taints:
      - key: "dfds.com/karpenter"
        value: "true"
        effect: "NoSchedule"
    spec:
      terminationGracePeriod: 5m
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t3"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: [medium, large, xlarge, 2xlarge]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2023-latest

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-spot
  annotations:
    kubernetes.io/description: "General purpose spot NodePool for generic workloads"
spec:
  limits:
    cpu: 32
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
  template:
    labels:
      - key: "dfds.com/nodegroup-purpose"
        value: "general"
    taints:
      - key: "dfds.com/karpenter"
        value: "true"
        effect: "NoSchedule"
      - key: "dfds.com/nodegroup-instance-spot"
        value: "spot"
        effect: "NoSchedule"
    spec:
      terminationGracePeriod: 5m
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t3"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: [medium, large, xlarge, 2xlarge]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2023-latest