---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-exporter-${flux_kafka_exporter_cluster_id}
  namespace: monitoring
spec:
  releaseName: kafka-exporter-${flux_kafka_exporter_cluster_id}
  serviceAccountName: helm-controller
  driftDetection:
    mode: enabled # kafka-exporter is not a traditional helm chart with releases, so it is consumed from master branch
  chart:
    spec:
      chart: chart
      reconcileStrategy: Revision # kafka-exporter is not a traditional helm chart with releases, so it is consumed from master branch
      sourceRef:
        kind: GitRepository
        name: kafka-exporter-${flux_kafka_exporter_cluster_id}
        namespace: monitoring
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    app:
      config:
        kafkaSecretRef: kafka-exporter-${flux_kafka_exporter_cluster_id}
      cluster:
        id: ${flux_kafka_exporter_cluster_id}
        environment: ${flux_kafka_exporter_environment}
    priorityClassName: cluster-observability
