---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kafka-exporter-${flux_kafka_exporter_cluster_id}
  namespace: monitoring
spec:
  interval: 1h0m0s
  ref:
    branch: master
  timeout: 60s
  url: https://github.com/dfds/kafka-exporter
