---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: 10.0.10
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  interval: 1m
  upgrade:
    force: true
  values:
    image:
      name: velero/velero
    cleanUpCRDs: true
    credentials:
      useSecret: false
    snapshotsEnabled: true
    configuration:
      logLevel: info
      logFormat: json
      backupStorageLocation:
      - provider: aws
        bucket: velero-storage
        config:
          region: eu-west-1
      volumeSnapshotLocation:
      - name: velero-snapshot
        provider: aws
        config:
          region: eu-west-1
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.12.1
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.5.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    priorityClassName: service-critical
    metrics:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 500m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
