---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  serviceAccountName: helm-controller
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: 11.3.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  interval: 1m
  upgrade:
    force: true
  values:
    image:
      name: velero/velero
    cleanUpCRDs: true
    credentials:
      useSecret: false
    snapshotsEnabled: true
    configuration:
      logLevel: info
      logFormat: json
      backupStorageLocation:
      - provider: aws
        bucket: velero-storage
        config:
          region: eu-west-1
      volumeSnapshotLocation:
      - name: velero-snapshot
        provider: aws
        config:
          region: eu-west-1
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.12.2
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.5.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    priorityClassName: cluster-infrastructure
    metrics:
      scrapeInterval: 120s
      serviceMonitor:
        enabled: true
        metricRelabelings:
          - sourceLabels: ["__name__"]
            regex: "velero_backup_validation_failure_total|velero_restore_failed_total|velero_restore_validation_failed_total|velero_volume_snapshot_failure_total"
            action: keep
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
