---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  serviceAccountName: helm-controller
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: 11.3.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    cleanUpCRDs: true
    configuration:
      backupStorageLocation:
      - bucket: ${flux_velero_aws_bucket_name}
        config:
          region: ${flux_aws_region}
        default: true
        name: default
        provider: aws
        accessMode: ${flux_velero_access_mode}
      - bucket: ${flux_velero_azure_bucket_name}
        config:
          resourceGroup: ${flux_velero_azure_resource_group}
          storageAccount: ${flux_velero_azure_storage_account}
          subscriptionId: ${flux_velero_azure_subscription_id}
        credential:
          key: cloud
          name: velero-credentials
        name: azure
        provider: azure
        accessMode: ${flux_velero_access_mode}
      features: EnableCSI
      logFormat: json
      volumeSnapshotLocation:
      - config:
          region: ${flux_aws_region}
        name: velero-snapshot
        provider: aws
      - bucket: ${flux_velero_azure_bucket_name}
        config:
          resourceGroup: ${flux_velero_azure_resource_group}
          subscriptionId: ${flux_velero_azure_subscription_id}
        credential:
          key: cloud
          name: velero-credentials
        name: azure-snapshot
        provider: azure
    credentials:
      useSecret: false
    deployNodeAgent: true
    initContainers:
    - image: velero/velero-plugin-for-aws:v1.13.2
      name: velero-plugin-for-aws
      volumeMounts:
      - mountPath: /target
        name: plugins
    - image: velero/velero-plugin-for-microsoft-azure:v1.12.1
      name: velero-plugin-for-microsoft-azure
      volumeMounts:
      - mountPath: /target
        name: plugins
    metrics:
      scrapeInterval: 120s
      serviceMonitor:
        enabled: true
        metricRelabelings:
        - action: keep
          regex: velero_backup_validation_failure_total|velero_restore_failed_total|velero_restore_validation_failed_total|velero_volume_snapshot_failure_total
          sourceLabels:
          - __name__
    priorityClassName: cluster-infrastructure
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 2Gi
    schedules:
      ${flux_cluster_name}-cluster-backup:
        disabled: ${flux_velero_cluster_backup_disabled}
        schedule: 0 0 * * *
        template:
          excludedNamespaceScopedResources:
          - secrets
          - configauditreports
          - exposedsecretreports
          - infraassessmentreports
          - rbacassessmentreports
          - sbomreports
          - vulnerabilityreports
          excludedNamespaces:
          - velero
          snapshotVolumes: true
          storageLocation: default
          ttl: 730h
      ${flux_cluster_name}-cluster-backup-offsite:
        disabled: ${flux_velero_cluster_backup_offsite_disabled}
        schedule: 0 * * * *
        template:
          excludedNamespaceScopedResources:
          - secrets
          - configauditreports
          - exposedsecretreports
          - infraassessmentreports
          - rbacassessmentreports
          - sbomreports
          - vulnerabilityreports
          excludedNamespaces:
          - velero
          snapshotMoveData: true
          snapshotVolumes: true
          storageLocation: azure
          ttl: 730h
          volumeSnapshotLocations:
          - azure-snapshot
    serviceAccount:
      server:
        annotations:
          eks.amazonaws.com/role-arn: ${flux_velero_iam_role_arn}
          eks.amazonaws.com/sts-regional-endpoints: "true"
        create: true
    snapshotsEnabled: true
