apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: velero-ssm
  namespace: velero
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: ssm-secrets
