---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  serviceAccountName: helm-controller
  releaseName: prometheus-blackbox-exporter
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 11.3.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 15s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
        http_401:
          prober: http
          timeout: 15s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            valid_status_codes: [401]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
    priorityClassName: cluster-observability
