apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: kyverno
spec:
  releaseName: policy-reporter
  serviceAccountName: helm-controller
  dependsOn:
    - name: kyverno
      namespace: kyverno
  chart:
    spec:
      chart: policy-reporter
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: kyverno
  interval: 1m0s
  targetNamespace: kyverno
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    resources:
      limits:
        memory: 384Mi
      requests:
        cpu: 200m
        memory: 384Mi
    priorityClassName: cluster-observability
    ui:
      enabled: true
      resources:
        limits:
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 64Mi
      priorityClassName: cluster-observability
    plugin:
      kyverno:
        enabled: true
        priorityClassName: cluster-observability
        resources: {} # todo: add once actually deployed