apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: kyverno
spec:
  releaseName: policy-reporter
  serviceAccountName: helm-controller
  dependsOn:
    - name: kyverno
      namespace: kyverno
  chart:
    spec:
      chart: policy-reporter
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: kyverno
  interval: 1m0s
  targetNamespace: kyverno
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ui:
      enabled: true
    kyvernoPlugin:
      enabled: true
    tolerations:
      - key: "dfds.com/karpenter"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "dfds.com/nodegroup-instance-spot" # delete this if you don't want spot-instances
        operator: "Exists"
        effect: "NoSchedule"
    nodeSelector:
      dfds.com/nodegroup-purpose: general # ensures you land on a Karpenter node

