---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: arc-systems
spec:
  serviceAccountName: helm-controller
  releaseName: arc
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
