---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: arc-systems
spec:
  serviceAccountName: helm-controller
  releaseName: arc
  chartRef:
    kind: OCIRepository
    name: arc
  interval: 10m0s
  install:
    remediation:
      retries: 3
