apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  releaseName: nvidia-device-plugin
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: nvidia-k8s-device-plugin
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    nodeSelector:
      karpenter.k8s.aws/instance-gpu-manufacturer: nvidia