apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  serviceAccountName: helm-controller
  releaseName: nvidia-device-plugin
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: nvidia-device-plugin
  interval: 1m0s
  install:
    remediation:
      retries: 3
