apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-arc-dfds
  namespace: arc-runners
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /arc/github-app-id
      metadataPolicy: None
    secretKey: github_app_id
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /arc/github-app-installation-id
      metadataPolicy: None
    secretKey: github_app_installation_id
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /arc/github-app-private-key
      metadataPolicy: None
    secretKey: github_app_private_key
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: ssm-eu-west-1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: github-arc-dfds
