---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-set
  namespace: arc-runners
spec:
  releaseName: arc-runner-set
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3