apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: ssm-eu-west-1
  namespace: arc-runners
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: ssm-secrets
      region: eu-west-1
      service: ParameterStore
