---
# Source: traefik/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-blue-variant
  namespace: traefik-blue-variant
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-blue-variant-traefik-blue-variant
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: traefik-blue-variant-traefik-blue-variant
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 0
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9100"
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik-blue-variant-traefik-blue-variant
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: traefik-blue-variant
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 320
      hostNetwork: false
      containers:
        - image: docker.io/traefik:v3.6.2
          imagePullPolicy: IfNotPresent
          name: traefik-blue-variant
          resources:
            limits:
              memory: 640Mi
            requests:
              cpu: 200m
              memory: 640Mi
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            failureThreshold: 1
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          lifecycle:
            preStop:
              sleep:
                seconds: 300
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
            - name: traefik
              containerPort: 8080
              protocol: TCP
            - name: web
              containerPort: 8000
              protocol: TCP
            - name: websecure
              containerPort: 8443
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          args:
            - "--entryPoints.metrics.address=:9100/tcp"
            - "--entryPoints.traefik.address=:8080/tcp"
            - "--entryPoints.web.address=:8000/tcp"
            - "--entryPoints.websecure.address=:8443/tcp"
            - "--api.dashboard=true"
            - "--ping=true"
            - "--metrics.prometheus=true"
            - "--metrics.prometheus.entrypoint=metrics"
            - "--providers.kubernetescrd"
            - "--providers.kubernetescrd.allowCrossNamespace=true"
            - "--providers.kubernetescrd.allowEmptyServices=true"
            - "--providers.kubernetesingress"
            - "--providers.kubernetesingress.allowEmptyServices=true"
            - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik-blue-variant/traefik-blue-variant"
            - "--providers.kubernetesgateway"
            - "--providers.kubernetesgateway.statusaddress.service.name=traefik-blue-variant"
            - "--providers.kubernetesgateway.statusaddress.service.namespace=traefik-blue-variant"
            - "--entryPoints.web.forwardedHeaders.insecure"
            - "--entryPoints.websecure.http.tls=true"
            - "--log.format=json"
            - "--log.level=ERROR"
            - "--accesslog=true"
            - "--accesslog.filters.statuscodes=300-399,400-499,500-599"
            - "--accesslog.fields.defaultmode=keep"
            - "--accesslog.fields.headers.defaultmode=drop"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: USER
              value: traefik
            - name: GOMEMLIMIT
              value: "576MiB"
      volumes:
        - name: data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      priorityClassName: cluster-infrastructure
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/instance: traefik-blue-variant-traefik-blue-variant
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
