---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    priorityClassName: cluster-infrastructure
    provider:
      name: aws
    sources:
      - crd
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        memory: 64Mi
    extraArgs:
      - --aws-prefer-cname
    managedRecordTypes:
      - A
      - AAAA
      - CNAME
    policy: upsert-only
    namespaced: true