apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: external-dns
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  interval: 1m
  install:
    crds: Skip
    remediation:
      retries: 3
  values:
    priorityClassName: cluster-infrastructure
    provider:
      name: aws
    env:
      - name: AWS_DEFAULT_REGION
        value: ${flux_aws_region}
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${flux_external_dns_role_arn}
    txtOwnerId: ${flux_cluster_name}-external-dns # changing this causes the controller to loose ownership of records
    extraArgs:
      - --aws-assume-role=${flux_external_dns_assume_role_arn}
      - --aws-prefer-cname
      - --namespace=external-dns
      - --zone-id-filter=${flux_external_dns_core_zone_id}
      - --zone-id-filter=${flux_external_dns_workload_zone_id}
    sources:
      - crd
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        memory: 64Mi
    managedRecordTypes:
      - A
      - AAAA
      - CNAME
    policy: upsert-only
