---
# Source: goldpinger/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goldpinger
  labels:
    app.kubernetes.io/name: goldpinger
    app.kubernetes.io/instance: goldpinger
    app.kubernetes.io/managed-by: Helm
