apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik-metrics
    scrape-service-metrics: "true"
  name: traefik-metrics
spec:
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  type: ClusterIP