---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-helm-exporter
  namespace: monitoring
spec:
  releaseName: prometheus-helm-exporter
  chart:
    spec:
      chart: helm-exporter
      sourceRef:
        kind: HelmRepository
        name: sstarcher
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    serviceMonitor:
      create: true
      scrapeTimeout: 10s
      additionalLabels:
        release: monitoring
   
             
