---
# Source: flink-kubernetes-operator/templates/flink/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink
  namespace: flink
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/resource-policy": keep
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
