---
# Source: flink-kubernetes-operator/templates/webhook/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flink-operator-webhook-secret
  namespace: flink
type: Opaque
data:
  password: cGFzc3dvcmQxMjM0
