---
# Source: flink-kubernetes-operator/templates/flink/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: flink
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/resource-policy: keep
