---
# Source: flink-kubernetes-operator/templates/rbac/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-operator
  namespace: flink
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/managed-by: Helm
