apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 1password-connect
  namespace: 1password-connect
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: 1password-connect-ssm
  target:
    name: op-credentials
    creationPolicy: Owner
  data:
    - secretKey: 1password-credentials.json
      remoteRef:
        key: /1password-connect/1password-credentials.json
