apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 1password-connect
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: 1password-connect-ssm
  target:
    name: op-credentials
    creationPolicy: Owner
  data:
    - secretKey: 1password-credentials.json
      remoteRef:
        key: /1password-connect/1password-credentials.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 1password-operator-token
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: 1password-connect-ssm
  target:
    name: onepassword-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /1password-connect/operator-token
