---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sources.yaml
  - release.yaml
  - serviceaccount.yaml
  - secretstore.yaml
  - externalsecret.yaml
