---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password-connect
spec:
  serviceAccountName: helm-controller
  releaseName: 1password-connect
  chart:
    spec:
      chart: connect
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: 1password-connect
        namespace: 1password-connect
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    connect:
      priorityClassName: "cluster-infrastructure"
