apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: 1password-connect-ssm
spec:
  provider:
    aws:
      service: ParameterStore
      region: ${flux_aws_region}
      auth:
        jwt:
          serviceAccountRef:
            name: 1password-connect
