apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: 1password-connect-ssm
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: 1password-connect