---
apiVersion: v1
kind: Namespace
metadata:
  name: fluentd

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-cloudwatch
  namespace: fluentd
spec:
  template:
    spec:
      serviceAccountName: fluentd-cloudwatch
      containers:
        - name: fluentd-cloudwatch
          env:
            - name: AWS_REGION
              value: "eu-west-1"
            - name: RETENTION_IN_DAYS
              value: "14"
            # Override default parser to match containerd's raw log format.
            - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
              value: /^(?<time>.+) (?<stream>stdout|stderr) (?<logtag>[FP]) (?<log>.+)$/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-cloudwatch
  namespace: fluentd
data:
  01-filter-concat.conf: |-
    # Concatenate partial log messages together, necessary with containerd container runtime.
    <filter kubernetes.**>
      @type concat
      key log
      partial_key logtag
      partial_value P
      separator ""
    </filter>
  02-tag.conf: |-
    # Tag with namespace and prefix with clustername
    <match kubernetes.**>
      @type rewrite_tag_filter
      <rule>
        key $.kubernetes.namespace_name
        pattern ^(.+)$
        tag /k8s/patrick/$1
      </rule>
    </match>

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-cloudwatch
  namespace: fluentd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::578530104510:role/eks-patrick-cloudwatchlogs
    eks.amazonaws.com/sts-regional-endpoints: "true"
