apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  targetNamespace: autoscaler
  chart:
    spec:
      chart: cluster-autoscaler
      version: 9.46.6
      sourceRef:
        kind: HelmRepository
        name: autoscaler
        namespace: flux-system
  interval: 1m
  timeout: 15m