apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  serviceAccountName: helm-controller
  targetNamespace: keda
  chart:
    spec:
      chart: keda
      version: 2.17.2
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  interval: 1m
  timeout: 15m
  values:
    crds:
      install: true
    enableServiceLinks: false
    operator:
      replicaCount: 3
    metricsServer:
      replicaCount: 3
    webhooks:
      replicaCount: 3
    priorityClassName: "system-cluster-critical"
