apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  serviceAccountName: helm-controller
  targetNamespace: falco
  chart:
    spec:
      chart: falco
      version: 6.2.2
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: falco
  interval: 1m
  timeout: 15m
  values:
    resources:
      requests:
        cpu: 25m
        memory: 1024Mi
      limits:
        cpu: null
        memory: 1024Mi
    controller:
      daemonset:
        updateStrategy:
          rollingUpdate:
            maxUnavailable: 25%
    podPriorityClassName: node-observability
    falcosidekick:
      priorityClassName: cluster-observability
      resources:
        requests:
          cpu: 5m
          memory: 256Mi
        limits:
          memory: 256Mi
      webui:
        priorityClassName: cluster-observability
        redis:
          priorityClassName: cluster-observability
    collectors:
      kubernetes:
        resources:
          requests:
            cpu: 5m
            memory: 512Mi
          limits:
            memory: 512Mi
