apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system
spec:
  serviceAccountName: helm-controller
  targetNamespace: falco
  chart:
    spec:
      chart: falco
      version: 6.2.2
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  interval: 1m
  timeout: 15m
  values:
    controller:
      daemonset:
        updateStrategy:
          rollingUpdate:
            maxUnavailable: 25%
    podPriorityClassName: node-observability
    falcosidekick:
      priorityClassName: cluster-observability
      webui:
        priorityClassName: cluster-observability
        redis:
          priorityClassName: cluster-observability
