apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system
spec:
  targetNamespace: falco
  chart:
    spec:
      chart: falco
      version: 6.2.3
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  interval: 1m
  timeout: 15m
  values
    podPriorityClassName: node-observability
    falcosidekick:
      priorityClassName: cluster-observability
      webui:
        priorityClassName: cluster-observability
        redis:
          priorityClassName: cluster-observability