---
# Source: vertical-pod-autoscaler/templates/admission-controller-certmanager.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vertical-pod-autoscaler-webhook-ca
  namespace: vertical-pod-autoscaler
  labels:
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/instance: vertical-pod-autoscaler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/component-instance: vertical-pod-autoscaler-admission-controller
spec:
  isCA: true
  secretName: vertical-pod-autoscaler-webhook-ca
  commonName: vertical-pod-autoscaler-webhook-ca
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: vertical-pod-autoscaler-selfsigned
    kind: Issuer
    group: cert-manager.io
  duration: 8760h
  renewBefore: 720h
