---
# Source: vertical-pod-autoscaler/templates/recommender-clusterrolebindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vertical-pod-autoscaler-recommender-checkpoint-actor
  labels:
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/instance: vertical-pod-autoscaler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: recommender
    app.kubernetes.io/component-instance: vertical-pod-autoscaler-recommender
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vertical-pod-autoscaler-recommender-checkpoint-actor
subjects:
  - kind: ServiceAccount
    name: vertical-pod-autoscaler-recommender
    namespace: vertical-pod-autoscaler
