---
# Source: vertical-pod-autoscaler/templates/updater-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vertical-pod-autoscaler-updater-evictioner-binding
  labels:
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/instance: vertical-pod-autoscaler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: updater
    app.kubernetes.io/component-instance: vertical-pod-autoscaler-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vertical-pod-autoscaler-updater-evictioner
subjects:
  - kind: ServiceAccount
    name: vertical-pod-autoscaler-updater
    namespace: vertical-pod-autoscaler
