---
# Source: vertical-pod-autoscaler/templates/admission-controller-certmanager.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vertical-pod-autoscaler-selfsigned
  namespace: vertical-pod-autoscaler
  labels:
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/instance: vertical-pod-autoscaler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/component-instance: vertical-pod-autoscaler-admission-controller
spec:
  selfSigned: {}
