---
# Source: vertical-pod-autoscaler/templates/updater-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vpa-vertical-pod-autoscaler-updater
  namespace: vpa
  labels:
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: updater
    app.kubernetes.io/component-instance: vpa-updater
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vertical-pod-autoscaler
      app.kubernetes.io/instance: vpa
      app.kubernetes.io/component: updater
  minAvailable: 1
