---
# Source: vertical-pod-autoscaler/templates/recommender-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vpa-vertical-pod-autoscaler-recommender
  namespace: vpa
  labels:
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: recommender
    app.kubernetes.io/component-instance: vpa-recommender
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vertical-pod-autoscaler
      app.kubernetes.io/instance: vpa
      app.kubernetes.io/component: recommender
  minAvailable: 1
