---
# Source: vertical-pod-autoscaler/templates/admission-controller-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vertical-pod-autoscaler-admission-controller
  namespace: vertical-pod-autoscaler
  labels:
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/instance: vertical-pod-autoscaler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/component-instance: vertical-pod-autoscaler-admission-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vertical-pod-autoscaler
      app.kubernetes.io/instance: vertical-pod-autoscaler
      app.kubernetes.io/component: admission-controller
  minAvailable: 1
