---
# Source: vertical-pod-autoscaler/templates/updater-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-updater
  namespace: vpa
  labels:
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: updater
    app.kubernetes.io/component-instance: vpa-updater
