apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trivy-operator-ssm
  namespace: trivy-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: trivy-operator-ssm
  target:
    name: trivy-operator-trivy-config
    creationPolicy: Owner
  data:
    - secretKey: trivy.githubToken
      remoteRef:
        key: /eks/${flux_cluster_name}/trivy-operator-github-token
