apiVersion: v1
kind: LimitRange
metadata:
  name: admission-resources
  namespace: trivy-system
spec:
  limits:
    - default:
        cpu: "1"
        memory: 256Mi
      defaultRequest:
        cpu: 20m
        memory: 64Mi
      max:
        cpu: "4"
        memory: 16Gi
      type: Container
    - max:
        cpu: "4"
        memory: 16Gi
      type: Pod
