apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  serviceAccountName: helm-controller
  releaseName: trivy-operator
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  chart:
    spec:
      chart: trivy-operator
      version: 0.31.0
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
        namespace: trivy-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    resources: # Resource requirements for the Trivy Operator.
      limits:
        memory: ${flux_trivy_operator_memory} # Post Build Substitution from Terraform
      requests:
        cpu: ${flux_trivy_operator_cpu} # Post Build Substitution from Terraform
        memory: ${flux_trivy_operator_memory} # Post Build Substitution from Terraform
    service:
      headless: false
    serviceMonitor:
      enabled: false
      namespace: trivy-system
    trivy:
      existingSecret: true
      ignoreUnfixed: true
      labels:
        scrape-service-metrics: "true"
      resources: # Resource requirements for the Trivy scan jobs.
        limits:
          cpu: null
          memory: ${flux_trivy_operator_scan_jobs_memory} # Post Build Substitution from Terraform
        requests:
          cpu: ${flux_trivy_operator_scan_jobs_cpu} # Post Build Substitution from Terraform
          memory: ${flux_trivy_operator_scan_jobs_memory} # Post Build Substitution from Terraform
    operator:
      labels:
        scrape-service-metrics: "true"
    nodeCollector:
      excludeNodes: "dedicated=cargoallocation,dedicated=dataplatform,dedicated=observability"
      tolerations:
        - operator: Exists
          effect: NoSchedule
