apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  serviceAccountName: helm-controller
  releaseName: trivy-operator
  chart:
    spec:
      chart: trivy-operator
      version: 0.31.0
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    resources: # Resource requirements for the Trivy Operator.
      limits:
        memory: 1Gi # Patch from Terraform if necessary
      requests:
        cpu: 100m
        memory: 1Gi # Patch from Terraform if necessary
    service:
      headless: false
    serviceMonitor:
      enabled: true
      namespace: trivy-system
    trivy:
      ignoreUnfixed: true
      labels:
        scrape-service-metrics: "true"
      resources: # Resource requirements for the Trivy scan jobs.
        limits:
          cpu: null
          memory: 512Mi # Patch from Terraform if necessary
        requests:
          cpu: 100m
          memory: 512Mi # Patch from Terraform if necessary
    operator:
      labels:
        scrape-service-metrics: "true"
    nodeCollector:
      tolerations:
        - operator: Exists
          effect: NoSchedule
