apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: trivy-operator-ssm
  namespace: trivy-system
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: trivy-operator
