apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-operator
  namespace: trivy-system
  annotations:
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/role-arn: "arn:aws:iam::${flux_workload_account_id}:role/${flux_cluster_name}-trivy-operator-irsa"
