---
# Source: k8s-monitoring/charts/alloy-events/templates/controllers/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-k8s-monitoring-alloy-events
  namespace: grafana
  labels:
    app.kubernetes.io/name: alloy-events
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: alloy
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy-events
      app.kubernetes.io/instance: grafana-k8s-monitoring
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: alloy
        k8s.grafana.com/logs.job: integrations/alloy
      labels:
        app.kubernetes.io/name: alloy-events
        app.kubernetes.io/instance: grafana-k8s-monitoring
    spec:
      serviceAccountName: grafana-k8s-monitoring-alloy-events
      containers:
        - name: alloy
          image: docker.io/grafana/alloy:v1.16.1
          imagePullPolicy: IfNotPresent
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/tmp/alloy
            - --server.http.listen-addr=0.0.0.0:12345
            - --server.http.ui-path-prefix=/
            - --stability.level=generally-available
          env:
            - name: ALLOY_DEPLOY_MODE
              value: "helm"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 12345
              name: http-metrics
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 12345
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
        - name: config-reloader
          image: quay.io/prometheus-operator/prometheus-config-reloader:v0.91.0@sha256:7d9e4eea5f1139e602508871f422b0116c60e87c662f3dcd234d5ab60cd0d8c1
          imagePullPolicy: IfNotPresent
          args:
            - --watched-dir=/etc/alloy
            - --reload-url=http://localhost:12345/-/reload
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
      priorityClassName: cluster-observability
      dnsPolicy: ClusterFirst
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: dedicated
                    operator: In
                    values:
                      - observability
              weight: 1
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          key: observability.dfds
          operator: Exists
      volumes:
        - name: config
          configMap:
            name: grafana-k8s-monitoring-alloy-events
