---
# Source: k8s-monitoring/charts/kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: grafana-k8s-monitoring
    jobLabel: kube-state-metrics
    release: grafana-k8s-monitoring
  name: grafana-k8s-monitoring-kube-state-metrics
  namespace: grafana
