apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: druid-operator
  namespace: druid-system
spec:
  chart:
    spec:
      chart: druid-operator
      version: 0.3.9
      sourceRef:
        kind: HelmRepository
        name: datainfra
        namespace: flux-system
  interval: 1m
  values:
    env:
      WATCH_NAMESPACE: ""
    installCRDS: true
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
