---
# Source: velero/templates/schedule.yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: velero-${flux_cluster_name}-cluster-backup
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "0 0 * * *"
  template:
    excludedClusterScopedResources:
      - clustercleanuppolicies.kyverno.io
      - clusterpolicies.kyverno.io
      - globalcontextentries.kyverno.io
      - deletingpolicies.policies.kyverno.io
      - generatingpolicies.policies.kyverno.io
      - imagevalidatingpolicies.policies.kyverno.io
      - mutatingpolicies.policies.kyverno.io
      - validatingpolicies.policies.kyverno.io
      - clusterephemeralreports.reports.kyverno.io
      - clustercompliancereports.aquasecurity.github.io
      - clusterconfigauditreports.aquasecurity.github.io
      - clusterinfraassessmentreports.aquasecurity.github.io
      - clusterrbacassessmentreports.aquasecurity.github.io
      - clustersbomreports.aquasecurity.github.io
      - clustervulnerabilityreports.aquasecurity.github.io
      - clusterpolicyreports.wgpolicyk8s.io
    excludedNamespaceScopedResources:
      - secrets
      - cleanuppolicies.kyverno.io
      - policies.kyverno.io
      - policyexceptions.kyverno.io
      - updaterequests.kyverno.io
      - namespaceddeletingpolicies.policies.kyverno.io
      - namespacedgeneratingpolicies.policies.kyverno.io
      - namespacedimagevalidatingpolicies.policies.kyverno.io
      - namespacedmutatingpolicies.policies.kyverno.io
      - namespacedvalidatingpolicies.policies.kyverno.io
      - policyexceptions.policies.kyverno.io
      - ephemeralreports.reports.kyverno.io
      - configauditreports.aquasecurity.github.io
      - exposedsecretreports.aquasecurity.github.io
      - infraassessmentreports.aquasecurity.github.io
      - rbacassessmentreports.aquasecurity.github.io
      - sbomreports.aquasecurity.github.io
      - vulnerabilityreports.aquasecurity.github.io
      - policyreports.wgpolicyk8s.io
    excludedNamespaces:
      - velero
      - atlantis
      - kyverno
    snapshotVolumes: true
    storageLocation: default
    ttl: 730h
