---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 5m
  url: oci://public.ecr.aws/karpenter/karpenter
  ref:
    tag: "1.6.3"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 5m
  targetNamespace: karpenter
  releaseName: karpenter
  chartRef:
    kind: OCIRepository
    name: karpenter
  values:
    nodeSelector:
      karpenter.sh/controller: "true"
    settings:
      clusterName: ${flux_cluster_name}
      interruptionQueue: Karpenter-${flux_cluster_name}
      featureGates:
        spotToSpotConsolidation: true
    controller:
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          memory: 1Gi