apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 5m
  serviceAccountName: helm-controller
  targetNamespace: karpenter
  releaseName: karpenter
  chartRef:
    kind: OCIRepository
    name: karpenter
  install:
    crds: Skip
  values:
    nodeSelector:
      karpenter.sh/controller: "true"
    settings:
      clusterName: ${flux_cluster_name}
      interruptionQueue: Karpenter-${flux_cluster_name}
      featureGates:
        spotToSpotConsolidation: true
    controller:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          memory: 512Mi