---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  serviceAccountName: helm-controller
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: 3.5.2
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    resources:
      limits:
        memory: "2048Mi"
    replicaCount: 3
    admissionController:
      container:
        resources:
          limits:
            memory: "2048Mi"
      replicas: 3
    features:
      # REMOVE AUTO UPDATES, IT'S FOR DEMO ONLY
      autoUpdateWebhooks:
        enabled: false
      forceFailurePolicyIgnore:
        enabled: false
    config:
      webhooks:
        namespaceSelector:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
                - kube-system
                - kyverno
                - flux-system
                - monitoring
