apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  serviceAccountName: helm-controller
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: 3.5.2
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    admissionController:
      container:
        resources:
          limits:
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 384Mi
      replicas: 3
      priorityClassName: cluster-infrastructure
      # serviceMonitor: # Disabled for now due cost
      #   enabled: true
      #   additionalLabels:
      #     scrape-service-metrics: "true"
    reportsController:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      priorityClassName: cluster-observability
    backgroundController:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      priorityClassName: cluster-infrastructure
    cleanupController:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      priorityClassName: cluster-infrastructure
    features:
      forceFailurePolicyIgnore:
        enabled: true
      omitEvents:
        eventTypes:
          - PolicyViolation  # Silence audit violation events
          - PolicyApplied    # Also silence successful policy application events
          - PolicySkipped    # Also silence skipped policy events
    metricsConfig:
      metricsExposure:
        kyverno_policy_results_total:
          disabledLabelDimensions: []
        kyverno_admission_requests_total:
          disabledLabelDimensions: []
        kyverno_admission_review_duration_seconds:
          disabledLabelDimensions: []
    config:
      # Allow Secrets to be scanned by background controller
      resourceFilters:
        - '[*,kyverno,*]'
        - '[Event,*,*]'
        - '[Node,*,*]'
        - '[Node/*,*,*]'
        - '[APIService,*,*]'
        - '[TokenReview,*,*]'
        - '[SubjectAccessReview,*,*]'
        - '[SelfSubjectAccessReview,*,*]'
        - '[Binding,*,*]'
        - '[LocalSubjectAccessReview,*,*]'
        - '[SelfSubjectRulesReview,*,*]'
      webhooks:
        namespaceSelector:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
                - kube-system
                - kyverno
                - flux-system
                - monitoring
