---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  serviceAccountName: helm-controller
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: 3.5.2
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    resources:
      limits:
        memory: "2048Mi"
    replicaCount: 3
    admissionController:
      container:
        resources:
          limits:
            memory: "2048Mi"
      replicas: 3
      serviceMonitor:
        enabled: true
        additionalLabels:
          # Metrics scraping enabled
          scrape-service-metrics: "true"
    features:
      forceFailurePolicyIgnore:
        enabled: true
    metricsConfig:
      metricsExposure:
        kyverno_policy_results_total:
          disabledLabelDimensions: []
        kyverno_admission_requests_total:
          disabledLabelDimensions: []
        kyverno_admission_review_duration_seconds:
          disabledLabelDimensions: []
    config:
      webhooks:
        namespaceSelector:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
                - kube-system
                - kyverno
                - flux-system
                - monitoring
