apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atlantis-ssm
  namespace: atlantis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: atlantis-ssm
  target:
    name: atlantis-ssm
    creationPolicy: Owner
  dataFrom:
  - find:
      path: /atlantis/${flux_cluster_name}
      name:
        regexp: .*
    rewrite:
    - regexp:
        source: "/atlantis/${flux_cluster_name}/(.*)"
        target: "$1"
