apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis
  namespace: atlantis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: atlantis-ssm
  target:
    name: atlantis-environment
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /atlantis
        name:
          regexp: .*
      rewrite:
        - regexp:
            source: "/atlantis/(.*)"
            target: "${1}"
    - find:
        path: /falco
        name:
          regexp: .*
      rewrite:
      - regexp:
          source: "/falco/(.*)"
          target: "${1}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 1password-connect-token
  namespace: atlantis
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: atlantis-ssm
  target:
    name: atlantis-1password-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /atlantis/1password-connect-token
