apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 1password-connect-token
  namespace: atlantis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: atlantis-ssm
  target:
    name: atlantis-1password-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /atlantis/1password-connect-token
