apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfigs
  namespace: atlantis
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: atlantis-ssm
  target:
    name: kubeconfigs
    creationPolicy: Owner
  data:
    # trunk-ignore(checkov/CKV_SECRET_6)
    - secretKey: kubeconfigs
      remoteRef:
        key: kubeconfigs
