apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlantis
  namespace: flux-system
spec:
  serviceAccountName: helm-controller
  releaseName: atlantis
  chart:
    spec:
      chart: atlantis
      version: 5.23.0
      sourceRef:
        kind: HelmRepository
        name: atlantis
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
  values:
    basicAuthSecretName: atlantis-basic-auth
    loadEnvFromSecrets:
      - atlantis-github-auth
    disableApply: true
    disableApplyAll: true
    environment:
      TG_LOG_FORMAT: bare
      ATLANTIS_DEFAULT_TF_DISTRIBUTION: opentofu
    environmentSecrets:
      - name: PRODUCTION_AWS_ACCESS_KEY_ID
        secretKeyRef:
          key: PRODUCTION_AWS_ACCESS_KEY_ID
          name: atlantis-environment
      - name: PRODUCTION_AWS_ACCOUNT_MANIFESTS_HARDENED_MONITORING_SLACK_TOKEN
        secretKeyRef:
          key: PRODUCTION_AWS_ACCOUNT_MANIFESTS_HARDENED_MONITORING_SLACK_TOKEN
          name: atlantis-environment
      - name: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_BROKER
        secretKeyRef:
          key: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_BROKER
          name: atlantis-environment
      - name: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_PASSWORD
        secretKeyRef:
          key: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_PASSWORD
          name: atlantis-environment
      - name: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_USERNAME
        secretKeyRef:
          key: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_USERNAME
          name: atlantis-environment
      - name: PRODUCTION_AWS_SECRET_ACCESS_KEY
        secretKeyRef:
          key: PRODUCTION_AWS_SECRET_ACCESS_KEY
          name: atlantis-environment
      - name: PRODUCTION_DATALAKE_AWS_ACCESS_KEY_ID
        secretKeyRef:
          key: PRODUCTION_DATALAKE_AWS_ACCESS_KEY_ID
          name: atlantis-environment
      - name: PRODUCTION_DATALAKE_AWS_SECRET_ACCESS_KEY
        secretKeyRef:
          key: PRODUCTION_DATALAKE_AWS_SECRET_ACCESS_KEY
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_1PASSWORD_API_KEY
        secretKeyRef:
          key: PRODUCTION_GRAFANA_1PASSWORD_API_KEY
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_AGENT_API_TOKEN
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_API_TOKEN
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_AGENT_LOKI_URL
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_LOKI_URL
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_AGENT_LOKI_USERNAME
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_LOKI_USERNAME
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_AGENT_PROMETHEUS_URL
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_PROMETHEUS_URL
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_AGENT_PROMETHEUS_USERNAME
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_PROMETHEUS_USERNAME
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_AGENT_TEMPO_URL
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_TEMPO_URL
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_AGENT_TEMPO_USERNAME
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_TEMPO_USERNAME
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_CLOUD_API_KEY
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_API_KEY
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_CLOUD_ARM_CLIENT_ID
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_ARM_CLIENT_ID
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_CLOUD_ARM_CLIENT_SECRET
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_ARM_CLIENT_SECRET
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_CLOUD_ARM_TENANT_ID
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_ARM_TENANT_ID
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_CLOUD_AZURE_SP_ADMIN_CONSENT_CLIENT_ID
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_AZURE_SP_ADMIN_CONSENT_CLIENT_ID
          name: atlantis-environment
      - name: PRODUCTION_GRAFANA_CLOUD_AZURE_SP_ADMIN_CONSENT_CLIENT_SECRET
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_AZURE_SP_ADMIN_CONSENT_CLIENT_SECRET
          name: atlantis-environment
      - name: PRODUCTION_PREPRIME_AWS_ACCESS_KEY_ID
        secretKeyRef:
          key: PRODUCTION_PREPRIME_AWS_ACCESS_KEY_ID
          name: atlantis-environment
      - name: PRODUCTION_PREPRIME_AWS_SECRET_ACCESS_KEY
        secretKeyRef:
          key: PRODUCTION_PREPRIME_AWS_SECRET_ACCESS_KEY
          name: atlantis-environment
      - name: PRODUCTION_PREPRIME_BACKUP_REPORTS_SLACK_WEBHOOK_URL
        secretKeyRef:
          key: PRODUCTION_PREPRIME_BACKUP_REPORTS_SLACK_WEBHOOK_URL
          name: atlantis-environment
      - name: PRODUCTION_PRIME_AWS_ACCESS_KEY_ID
        secretKeyRef:
          key: PRODUCTION_PRIME_AWS_ACCESS_KEY_ID
          name: atlantis-environment
      - name: PRODUCTION_PRIME_AWS_SECRET_ACCESS_KEY
        secretKeyRef:
          key: PRODUCTION_PRIME_AWS_SECRET_ACCESS_KEY
          name: atlantis-environment
      - name: PRODUCTION_TF_VAR_slack_webhook_url
        secretKeyRef:
          key: PRODUCTION_TF_VAR_slack_webhook_url
          name: atlantis-environment
      - name: SHARED_ARM_CLIENT_ID
        secretKeyRef:
          key: SHARED_ARM_CLIENT_ID
          name: atlantis-environment
      - name: SHARED_ARM_CLIENT_SECRET
        secretKeyRef:
          key: SHARED_ARM_CLIENT_SECRET
          name: atlantis-environment
      - name: SHARED_ARM_SUBSCRIPTION_ID
        secretKeyRef:
          key: SHARED_ARM_SUBSCRIPTION_ID
          name: atlantis-environment
      - name: SHARED_ARM_TENANT_ID
        secretKeyRef:
          key: SHARED_ARM_TENANT_ID
          name: atlantis-environment
      - name: SHARED_TF_VAR_atlantis_github_token
        secretKeyRef:
          key: SHARED_TF_VAR_atlantis_github_token
          name: atlantis-environment
      - name: SHARED_TF_VAR_fluxcd_bootstrap_repo_owner_token
        secretKeyRef:
          key: SHARED_TF_VAR_fluxcd_bootstrap_repo_owner_token
          name: atlantis-environment
      - name: STAGING_AWS_ACCESS_KEY_ID
        secretKeyRef:
          key: STAGING_AWS_ACCESS_KEY_ID
          name: atlantis-environment
      - name: STAGING_AWS_SECRET_ACCESS_KEY
        secretKeyRef:
          key: STAGING_AWS_SECRET_ACCESS_KEY
          name: atlantis-environment
      - name: STAGING_GRAFANA_AGENT_API_TOKEN
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_API_TOKEN
          name: atlantis-environment
      - name: STAGING_GRAFANA_AGENT_LOKI_URL
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_LOKI_URL
          name: atlantis-environment
      - name: STAGING_GRAFANA_AGENT_LOKI_USERNAME
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_LOKI_USERNAME
          name: atlantis-environment
      - name: STAGING_GRAFANA_AGENT_PROMETHEUS_URL
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_PROMETHEUS_URL
          name: atlantis-environment
      - name: STAGING_GRAFANA_AGENT_PROMETHEUS_USERNAME
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_PROMETHEUS_USERNAME
          name: atlantis-environment
      - name: STAGING_GRAFANA_AGENT_TEMPO_URL
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_TEMPO_URL
          name: atlantis-environment
      - name: STAGING_GRAFANA_AGENT_TEMPO_USERNAME
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_TEMPO_USERNAME
          name: atlantis-environment
      - name: DS_SSU_VM_ENDPOINT
        secretKeyRef:
          key: DS_SSU_VM_ENDPOINT
          name: atlantis-environment
      - name: DS_SSU_VM_USERNAME
        secretKeyRef:
          key: DS_SSU_VM_USERNAME
          name: atlantis-environment
      - name: DS_SSU_VM_USERNAME
        secretKeyRef:
          key: DS_SSU_VM_USERNAME
          name: atlantis-environment
      - name: STAGING_TF_VAR_slack_webhook_url
        secretKeyRef:
          key: STAGING_TF_VAR_slack_webhook_url
          name: atlantis-environment
      - name: STAGING_TF_VAR_falco_slack_alert_webhook_url
        secretKeyRef:
          key: STAGING_TF_VAR_falco_slack_alert_webhook_url
          name: atlantis-environment
      - name: STAGING_TF_VAR_falco_stream_webhook_url
        secretKeyRef:
          key: STAGING_TF_VAR_falco_stream_webhook_url
          name: atlantis-environment
      - name: PRODUCTION_TF_VAR_falco_slack_alert_webhook_url
        secretKeyRef:
          key: PRODUCTION_TF_VAR_falco_slack_alert_webhook_url
          name: atlantis-environment
      - name: PRODUCTION_TF_VAR_falco_stream_webhook_url
        secretKeyRef:
          key: PRODUCTION_TF_VAR_falco_stream_webhook_url
          name: atlantis-environment
      - name: PRODUCTION_ONEPASSWORD_CREDENTIALS_JSON
        secretKeyRef:
          key: PRODUCTION_ONEPASSWORD_CREDENTIALS_JSON
          name: atlantis-environment
      - name: PRODUCTION_ONEPASSWORD_TOKEN_FOR_ATLANTIS
        secretKeyRef:
          key: PRODUCTION_ONEPASSWORD_TOKEN_FOR_ATLANTIS
          name: atlantis-environment
      - name: STAGING_ONEPASSWORD_CREDENTIALS_JSON
        secretKeyRef:
          key: STAGING_ONEPASSWORD_CREDENTIALS_JSON
          name: atlantis-environment
      - name: STAGING_ONEPASSWORD_TOKEN_FOR_ATLANTIS
        secretKeyRef:
          key: STAGING_ONEPASSWORD_TOKEN_FOR_ATLANTIS
          name: atlantis-environment
      - name: SHARED_docker_hub_username
        secretKeyRef:
          key: SHARED_docker_hub_username
          name: atlantis-environment
      - name: SHARED_docker_hub_password
        secretKeyRef:
          key: SHARED_docker_hub_password
          name: atlantis-environment
      - name: SHARED_docker_hub_token
        secretKeyRef:
          key: SHARED_docker_hub_token
          name: atlantis-environment
      - name: SHARED_eks_addon_awsebscsidriver_kms_arn
        secretKeyRef:
          key: SHARED_eks_addon_awsebscsidriver_kms_arn
          name: atlantis-environment
      - name: DEVELOPER_PLATFORM_DEPLOY_AWS_ACCESS_KEY_ID
        secretKeyRef:
          key: DEVELOPER_PLATFORM_DEPLOY_AWS_ACCESS_KEY_ID
          name: atlantis-environment
      - name: DEVELOPER_PLATFORM_DEPLOY_AWS_SECRET_ACCESS_KEY
        secretKeyRef:
          key: DEVELOPER_PLATFORM_DEPLOY_AWS_SECRET_ACCESS_KEY
          name: atlantis-environment
      - name: STAGING_velero_azure_subscription_id
        secretKeyRef:
          key: STAGING_velero_azure_subscription_id
          name: atlantis-environment
      - name: STAGING_velero_azure_resource_group_name
        secretKeyRef:
          key: STAGING_velero_azure_resource_group_name
          name: atlantis-environment
      - name: STAGING_velero_azure_storage_account_name
        secretKeyRef:
          key: STAGING_velero_azure_storage_account_name
          name: atlantis-environment
      - name: PRODUCTION_velero_azure_subscription_id
        secretKeyRef:
          key: PRODUCTION_velero_azure_subscription_id
          name: atlantis-environment
      - name: PRODUCTION_velero_azure_resource_group_name
        secretKeyRef:
          key: PRODUCTION_velero_azure_resource_group_name
          name: atlantis-environment
      - name: PRODUCTION_velero_azure_storage_account_name
        secretKeyRef:
          key: PRODUCTION_velero_azure_storage_account_name
          name: atlantis-environment
    extraArgs:
      - --parallel-pool-size=15
      - --default-tf-distribution=opentofu
    image:
      pullPolicy: IfNotPresent
      repository: dfdsdk/atlantis-prime-pipeline
      tag: 2.1.2
    ingress:
      enabled: true
      path: /
      annotations:
        kubernetes.io/ingress.class: traefik
      host: "atlantis.${flux_eks_fqdn}" # Post Build Substitution from Terraform
    logLevel: info
    orgAllowlist: ${flux_atlantis_org_allowlist} # Post Build Substitution from Terraform
    repoConfig: |
      ---
      repos:
      - id: "/.*/"
        allowed_overrides: [workflow]
        allow_custom_workflows: true
    resources: # Post Build Substitution from Terraform
      limits:
        memory: ${flux_atlantis_resource_memory}
      requests:
        cpu: ${flux_atlantis_resource_cpu}
        memory: ${flux_atlantis_resource_memory}
    service:
      type: ClusterIP
    serviceAccount:
      create: true
      name: atlantis
      annotations: # Post Build Substitution from Terraform
        eks.amazonaws.com/role-arn: arn:aws:iam::${flux_workload_account_id}:role/atlantis-irsa
        eks.amazonaws.com/sts-regional-endpoints: "true"
    statefulSet:
      securityContext:
        runAsUser: 200
      priorityClassName: cluster-infrastructure
    volumeClaim:
      dataStorage: 100Gi
      storageClassName: csi-gp3
    extraVolumeMounts:
      - mountPath: /kubeconfigs
        name: kubeconfigs
        readOnly: true
    extraVolumes:
      - name: kubeconfigs
        secret:
          defaultMode: 420
          secretName: kubeconfigs # pragma: allowlist secret
