apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlantis
  namespace: flux-system
spec:
  releaseName: atlantis
  chart:
    spec:
      chart: atlantis
      version: 5.7.0
      sourceRef:
        kind: HelmRepository
        name: atlantis
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
  values:
    disableApply: true
    disableApplyAll: true
    environmentSecrets:
      - name: CONFLUENT_KAFKA_PROD_PROMETHEUS_METRICS_EXPORTER_HELLMAN_API_KEY
        secretKeyRef:
          key: CONFLUENT_KAFKA_PROD_PROMETHEUS_METRICS_EXPORTER_HELLMAN_API_KEY
          name: env-secrets
      - name: CONFLUENT_KAFKA_PROD_PROMETHEUS_METRICS_EXPORTER_HELLMAN_API_SECRET
        secretKeyRef:
          key: CONFLUENT_KAFKA_PROD_PROMETHEUS_METRICS_EXPORTER_HELLMAN_API_SECRET
          name: env-secrets
      - name: PRODUCTION_AWS_ACCESS_KEY_ID
        secretKeyRef:
          key: PRODUCTION_AWS_ACCESS_KEY_ID
          name: env-secrets
      - name: PRODUCTION_AWS_ACCOUNT_MANIFESTS_HARDENED_MONITORING_SLACK_TOKEN
        secretKeyRef:
          key: PRODUCTION_AWS_ACCOUNT_MANIFESTS_HARDENED_MONITORING_SLACK_TOKEN
          name: env-secrets
      - name: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_BROKER
        secretKeyRef:
          key: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_BROKER
          name: env-secrets
      - name: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_PASSWORD
        secretKeyRef:
          key: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_PASSWORD
          name: env-secrets
      - name: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_USERNAME
        secretKeyRef:
          key: PRODUCTION_AWS_ACCOUNT_MANIFESTS_KAFKA_USERNAME
          name: env-secrets
      - name: PRODUCTION_AWS_SECRET_ACCESS_KEY
        secretKeyRef:
          key: PRODUCTION_AWS_SECRET_ACCESS_KEY
          name: env-secrets
      - name: PRODUCTION_GRAFANA_1PASSWORD_API_KEY
        secretKeyRef:
          key: PRODUCTION_GRAFANA_1PASSWORD_API_KEY
          name: env-secrets
      - name: PRODUCTION_GRAFANA_AGENT_API_TOKEN
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_API_TOKEN
          name: env-secrets
      - name: PRODUCTION_GRAFANA_AGENT_LOKI_URL
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_LOKI_URL
          name: env-secrets
      - name: PRODUCTION_GRAFANA_AGENT_LOKI_USERNAME
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_LOKI_USERNAME
          name: env-secrets
      - name: PRODUCTION_GRAFANA_AGENT_PROMETHEUS_URL
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_PROMETHEUS_URL
          name: env-secrets
      - name: PRODUCTION_GRAFANA_AGENT_PROMETHEUS_USERNAME
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_PROMETHEUS_USERNAME
          name: env-secrets
      - name: PRODUCTION_GRAFANA_AGENT_TEMPO_URL
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_TEMPO_URL
          name: env-secrets
      - name: PRODUCTION_GRAFANA_AGENT_TEMPO_USERNAME
        secretKeyRef:
          key: PRODUCTION_GRAFANA_AGENT_TEMPO_USERNAME
          name: env-secrets
      - name: PRODUCTION_GRAFANA_CLOUD_API_KEY
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_API_KEY
          name: env-secrets
      - name: PRODUCTION_GRAFANA_CLOUD_ARM_CLIENT_ID
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_ARM_CLIENT_ID
          name: env-secrets
      - name: PRODUCTION_GRAFANA_CLOUD_ARM_CLIENT_SECRET
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_ARM_CLIENT_SECRET
          name: env-secrets
      - name: PRODUCTION_GRAFANA_CLOUD_ARM_TENANT_ID
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_ARM_TENANT_ID
          name: env-secrets
      - name: PRODUCTION_GRAFANA_CLOUD_SSO_SAML_CERTIFICATE
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_SSO_SAML_CERTIFICATE
          name: env-secrets
      - name: PRODUCTION_GRAFANA_CLOUD_SSO_SAML_IDP_METADATA_URL
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_SSO_SAML_IDP_METADATA_URL
          name: env-secrets
      - name: PRODUCTION_GRAFANA_CLOUD_SSO_SAML_PRIVATE_KEY
        secretKeyRef:
          key: PRODUCTION_GRAFANA_CLOUD_SSO_SAML_PRIVATE_KEY
          name: env-secrets
      - name: PRODUCTION_PREPRIME_AWS_ACCESS_KEY_ID
        secretKeyRef:
          key: PRODUCTION_PREPRIME_AWS_ACCESS_KEY_ID
          name: env-secrets
      - name: PRODUCTION_PREPRIME_AWS_SECRET_ACCESS_KEY
        secretKeyRef:
          key: PRODUCTION_PREPRIME_AWS_SECRET_ACCESS_KEY
          name: env-secrets
      - name: PRODUCTION_PREPRIME_BACKUP_REPORTS_SLACK_WEBHOOK_URL
        secretKeyRef:
          key: PRODUCTION_PREPRIME_BACKUP_REPORTS_SLACK_WEBHOOK_URL
          name: env-secrets
      - name: PRODUCTION_PRIME_AWS_ACCESS_KEY_ID
        secretKeyRef:
          key: PRODUCTION_PRIME_AWS_ACCESS_KEY_ID
          name: env-secrets
      - name: PRODUCTION_PRIME_AWS_SECRET_ACCESS_KEY
        secretKeyRef:
          key: PRODUCTION_PRIME_AWS_SECRET_ACCESS_KEY
          name: env-secrets
      - name: PRODUCTION_TF_VAR_monitoring_kube_prometheus_stack_slack_webhook
        secretKeyRef:
          key: PRODUCTION_TF_VAR_monitoring_kube_prometheus_stack_slack_webhook
          name: env-secrets
      - name: PRODUCTION_TF_VAR_slack_webhook_url
        secretKeyRef:
          key: PRODUCTION_TF_VAR_slack_webhook_url
          name: env-secrets
      - name: SHARED_ARM_CLIENT_ID
        secretKeyRef:
          key: SHARED_ARM_CLIENT_ID
          name: env-secrets
      - name: SHARED_ARM_CLIENT_SECRET
        secretKeyRef:
          key: SHARED_ARM_CLIENT_SECRET
          name: env-secrets
      - name: SHARED_ARM_SUBSCRIPTION_ID
        secretKeyRef:
          key: SHARED_ARM_SUBSCRIPTION_ID
          name: env-secrets
      - name: SHARED_ARM_TENANT_ID
        secretKeyRef:
          key: SHARED_ARM_TENANT_ID
          name: env-secrets
      - name: SHARED_TF_VAR_atlantis_github_token
        secretKeyRef:
          key: SHARED_TF_VAR_atlantis_github_token
          name: env-secrets
      - name: SHARED_TF_VAR_fluxcd_bootstrap_repo_owner_token
        secretKeyRef:
          key: SHARED_TF_VAR_fluxcd_bootstrap_repo_owner_token
          name: env-secrets
      - name: SHARED_TF_VAR_monitoring_kube_prometheus_stack_azure_tenant_id
        secretKeyRef:
          key: SHARED_TF_VAR_monitoring_kube_prometheus_stack_azure_tenant_id
          name: env-secrets
      - name: STAGING_AWS_ACCESS_KEY_ID
        secretKeyRef:
          key: STAGING_AWS_ACCESS_KEY_ID
          name: env-secrets
      - name: STAGING_AWS_SECRET_ACCESS_KEY
        secretKeyRef:
          key: STAGING_AWS_SECRET_ACCESS_KEY
          name: env-secrets
      - name: STAGING_GRAFANA_AGENT_API_TOKEN
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_API_TOKEN
          name: env-secrets
      - name: STAGING_GRAFANA_AGENT_LOKI_URL
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_LOKI_URL
          name: env-secrets
      - name: STAGING_GRAFANA_AGENT_LOKI_USERNAME
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_LOKI_USERNAME
          name: env-secrets
      - name: STAGING_GRAFANA_AGENT_PROMETHEUS_URL
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_PROMETHEUS_URL
          name: env-secrets
      - name: STAGING_GRAFANA_AGENT_PROMETHEUS_USERNAME
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_PROMETHEUS_USERNAME
          name: env-secrets
      - name: STAGING_GRAFANA_AGENT_TEMPO_URL
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_TEMPO_URL
          name: env-secrets
      - name: STAGING_GRAFANA_AGENT_TEMPO_USERNAME
        secretKeyRef:
          key: STAGING_GRAFANA_AGENT_TEMPO_USERNAME
          name: env-secrets
      - name: STAGING_TF_VAR_monitoring_kube_prometheus_stack_slack_webhook
        secretKeyRef:
          key: STAGING_TF_VAR_monitoring_kube_prometheus_stack_slack_webhook
          name: env-secrets
      - name: STAGING_TF_VAR_slack_webhook_url
        secretKeyRef:
          key: STAGING_TF_VAR_slack_webhook_url
          name: env-secrets
    extraArgs:
      - --parallel-pool-size=15
    github: {} # Patch this from Terraform
    image:
      pullPolicy: IfNotPresent
      repository: dfdsdk/atlantis-prime-pipeline
      tag: 2.0.2
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        # trunk-ignore(checkov/CKV_SECRET_6)
        traefik.ingress.kubernetes.io/auth-secret: atlantis-dashboard
        traefik.ingress.kubernetes.io/auth-type: basic
      host: alias.example.tld # Patch this from Terraform
    webhook_ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      host: alias-two.example.tld # Patch this from Terraform
    logLevel: info
    orgAllowlist: "" # Patch this from Terraform
    repoConfig: |
      ---
      repos:
      - id: "/.*/"
        allowed_overrides: [workflow]
        allow_custom_workflows: true
    resources: # Patch this from Terraform
      limits:
        cpu: 100m
        memory: 1536Mi
      requests:
        cpu: 100m
        memory: 1536Mi
    service:
      type: ClusterIP
    statefulSet:
      securityContext:
        runAsUser: 200
    volumeClaim: # Patch this from Terraform
      dataStorage: 5Gi
      storageClassName: csi-gp3
    serviceAccount:
      create: true
      annotations: {} # Patch this from Terraform when using IRSA
