apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: atlantis-ssm
  namespace: atlantis
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: atlantis
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: atlantis-1password
  namespace: atlantis
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password-connect.svc.cluster.local:8080
      vaults:
        CloudEng-Grafana-Sharing: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: atlantis-1password-token
            key: token
---
apiVersion: external-secrets.io/v1beta1 # TODO: Delete me after testing
kind: ExternalSecret
metadata:
  name: my-env-config
  namespace: atlantis
spec:
  secretStoreRef:
    kind: SecretStore
    name: atlantis-1password
  target:
    creationPolicy: Owner
  data:
  - secretKey: MY_ENV_VAR1
    remoteRef:
      key: my-env-config
      property: MY_ENV_VAR1
  - secretKey: MY_ENV_VAR2
    remoteRef:
      key: my-env-config
      property: MY_ENV_VAR2
  refreshInterval: "1m"
---