apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: atlantis-ssm
  namespace: atlantis
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: atlantis
