apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-ssm
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: grafana-ssm
  target:
    name: onepassword-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: 1password-connect-token
      remoteRef:
        key: /eks/${flux_cluster_name}/1password-connect-token-grafana
