apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-k8s-monitoring-test
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: grafana-1password
  target:
    name: prometheus-k8s-monitoring-test
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: Grafana.com - platform
        property: Prometheus_URL
    - secretKey: password
      remoteRef:
        key: Grafana.com - platform
        property: grafana_token
    - secretKey: username
      remoteRef:
        key: Grafana.com - platform
        property: Prometheus_Username