apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - secretstore-ssm.yaml
  - externalsecret-1password-auth.yaml
  - secretstore-1password.yaml
  - externalsecret-alloy.yaml
  - sources.yaml
  - release.yaml
  - servicemonitor.yaml
