apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: grafana-1password
  namespace: grafana
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password-connect.svc.cluster.local:8080
      vaults:
        CloudEng-General: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-basic-auth
            key: 1password-connect-token
