apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: grafana-ssm
  namespace: grafana
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: grafana
