---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-lb-controller
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRVGk0b3NweVRPYllPd3ZjbGlmVjVKREFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE13TXpBNE5UQXpNMW9YRFRNMk1ESXlPVEE0TlRBek0xb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTmxET29pUDZJcTBxVy8xR0xFZnFXOERwb0FRa1UvZjFvQ3NvdGkrSWtFRTNUa0FPWi85eDE0RQo3cy82WlNpYzJZZzlyd0RrYXFFMy9IM3hoVTBzZTdJOFB2QkZFbVJVZUJCTGJ6bkk2RzBBUWNocU85RDVRMDNoCmUyK2FyU1FiWnA3TGduVG9pZ3g4SjUybWVFcGhORDU2T2Jic1MrZEMxb1NsVWdvM2Q5cGZVVHFxZlFxb0VOYmgKeG9nS2NYWjdMYzJtNUpOT3VUZC9VM0dLd3NQdlZXeFVKRnBhR0FlcHJJQi9iOFQxajRGcWc2OHptaW9YL09iagp0cUZ3ODFpbnJNY2hlTU5EZmNNaXg4bkRaK2hsTk51WkYvd20xTE5iTWhBdjBsaE9iLzFGVzhsejJ4V3Uwd0ZyCjJCK0xVc0I3Tmh3M0RhOUxpL05WblJHQUMxdm95dlVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlJvcE56UEovcjF3UXB6VE9GY3hCb0FPUlNBUnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFoNytPZDd6bWJ5YUhEZ1pDblJOeWJSdXpmOTBQcUJxc3BNcmNEZ3Q3eGZnWFA4TEUyUUtPbUhtK2I1NGUKKzlFM0p1SWlmTnZuU1hibHo5cW1Ia0hpdmdkbktiZU9TZWlrMUhuaEoyZEJEa0dPckM3ck0xazNWVGFKME1uRgprVXJKRUtHa3ZLQ1hzVHZDY2R0V3UyU2c5dGJPQU1MYWJBT2V3d00vTytDZWdOT1JLbSt2Vm9QL0RLczBsYm1oCmg5cVhEdGJmRk42L29peWt2WCtPb0ZVN2tvV3N1cW12eGVBaTRsZFU5anNXU0FDZUtDM2RZU3ZjMng4NXI4L2gKTzFHbHlxYWVURit2QVNpNHR0Tm1YVkg4dEdZVXB6dVpDK21RSEZnZnhOc1p5SGJ3NlAybFhpQ1ZJRlh1YXQ5OQpqZkU1ZkhNVmZ2MllHYjlUL090cFpaRjFOQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-v1-pod
    failurePolicy: Ignore
    name: mpod.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/pod-readiness-gate-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRVGk0b3NweVRPYllPd3ZjbGlmVjVKREFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE13TXpBNE5UQXpNMW9YRFRNMk1ESXlPVEE0TlRBek0xb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTmxET29pUDZJcTBxVy8xR0xFZnFXOERwb0FRa1UvZjFvQ3NvdGkrSWtFRTNUa0FPWi85eDE0RQo3cy82WlNpYzJZZzlyd0RrYXFFMy9IM3hoVTBzZTdJOFB2QkZFbVJVZUJCTGJ6bkk2RzBBUWNocU85RDVRMDNoCmUyK2FyU1FiWnA3TGduVG9pZ3g4SjUybWVFcGhORDU2T2Jic1MrZEMxb1NsVWdvM2Q5cGZVVHFxZlFxb0VOYmgKeG9nS2NYWjdMYzJtNUpOT3VUZC9VM0dLd3NQdlZXeFVKRnBhR0FlcHJJQi9iOFQxajRGcWc2OHptaW9YL09iagp0cUZ3ODFpbnJNY2hlTU5EZmNNaXg4bkRaK2hsTk51WkYvd20xTE5iTWhBdjBsaE9iLzFGVzhsejJ4V3Uwd0ZyCjJCK0xVc0I3Tmh3M0RhOUxpL05WblJHQUMxdm95dlVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlJvcE56UEovcjF3UXB6VE9GY3hCb0FPUlNBUnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFoNytPZDd6bWJ5YUhEZ1pDblJOeWJSdXpmOTBQcUJxc3BNcmNEZ3Q3eGZnWFA4TEUyUUtPbUhtK2I1NGUKKzlFM0p1SWlmTnZuU1hibHo5cW1Ia0hpdmdkbktiZU9TZWlrMUhuaEoyZEJEa0dPckM3ck0xazNWVGFKME1uRgprVXJKRUtHa3ZLQ1hzVHZDY2R0V3UyU2c5dGJPQU1MYWJBT2V3d00vTytDZWdOT1JLbSt2Vm9QL0RLczBsYm1oCmg5cVhEdGJmRk42L29peWt2WCtPb0ZVN2tvV3N1cW12eGVBaTRsZFU5anNXU0FDZUtDM2RZU3ZjMng4NXI4L2gKTzFHbHlxYWVURit2QVNpNHR0Tm1YVkg4dEdZVXB6dVpDK21RSEZnZnhOc1p5SGJ3NlAybFhpQ1ZJRlh1YXQ5OQpqZkU1ZkhNVmZ2MllHYjlUL090cFpaRjFOQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-v1-service
    failurePolicy: Fail
    name: mservice.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - services
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRVGk0b3NweVRPYllPd3ZjbGlmVjVKREFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE13TXpBNE5UQXpNMW9YRFRNMk1ESXlPVEE0TlRBek0xb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTmxET29pUDZJcTBxVy8xR0xFZnFXOERwb0FRa1UvZjFvQ3NvdGkrSWtFRTNUa0FPWi85eDE0RQo3cy82WlNpYzJZZzlyd0RrYXFFMy9IM3hoVTBzZTdJOFB2QkZFbVJVZUJCTGJ6bkk2RzBBUWNocU85RDVRMDNoCmUyK2FyU1FiWnA3TGduVG9pZ3g4SjUybWVFcGhORDU2T2Jic1MrZEMxb1NsVWdvM2Q5cGZVVHFxZlFxb0VOYmgKeG9nS2NYWjdMYzJtNUpOT3VUZC9VM0dLd3NQdlZXeFVKRnBhR0FlcHJJQi9iOFQxajRGcWc2OHptaW9YL09iagp0cUZ3ODFpbnJNY2hlTU5EZmNNaXg4bkRaK2hsTk51WkYvd20xTE5iTWhBdjBsaE9iLzFGVzhsejJ4V3Uwd0ZyCjJCK0xVc0I3Tmh3M0RhOUxpL05WblJHQUMxdm95dlVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlJvcE56UEovcjF3UXB6VE9GY3hCb0FPUlNBUnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFoNytPZDd6bWJ5YUhEZ1pDblJOeWJSdXpmOTBQcUJxc3BNcmNEZ3Q3eGZnWFA4TEUyUUtPbUhtK2I1NGUKKzlFM0p1SWlmTnZuU1hibHo5cW1Ia0hpdmdkbktiZU9TZWlrMUhuaEoyZEJEa0dPckM3ck0xazNWVGFKME1uRgprVXJKRUtHa3ZLQ1hzVHZDY2R0V3UyU2c5dGJPQU1MYWJBT2V3d00vTytDZWdOT1JLbSt2Vm9QL0RLczBsYm1oCmg5cVhEdGJmRk42L29peWt2WCtPb0ZVN2tvV3N1cW12eGVBaTRsZFU5anNXU0FDZUtDM2RZU3ZjMng4NXI4L2gKTzFHbHlxYWVURit2QVNpNHR0Tm1YVkg4dEdZVXB6dVpDK21RSEZnZnhOc1p5SGJ3NlAybFhpQ1ZJRlh1YXQ5OQpqZkU1ZkhNVmZ2MllHYjlUL090cFpaRjFOQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: mtargetgroupbinding.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
