---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-load-balancer-tls
  namespace: aws-lb-controller
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-lb-controller
type: kubernetes.io/tls
data:
  ca.crt: REPLACED
  tls.crt: REPLACED
  tls.key: REPLACED
