---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-lb-controller
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQVA4NlhwUjdEeFpNVnBPbUF1b204d0l3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TURNeE1ETTJNRFZhRncwek5qQXlNamt4TURNMk1EVmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURCenpjL0FXeXRic3hXSGR1empjc2F6RlV5c1dJcEFIWjNLL0JGMEd5ZiszTnVwT2w1My94cAphRXhUZGdPUE55cjg3TGNSZlZESlhNdUZ1cGtQTHVyZnBPUGFHMk9WYVFSNi8rREg3eVlkQ0ZaeUpzNTdqdjVXClhpRTA3cDNueEJ4R0tZNm9QR0xqTVBDMmhIRXFJN2FCZXd2SXBpeENlZGM4VUlFZHdnTllJaGJqemJkZHRQdmsKSnpGZ3lwR3Z6NFpxcVVaTmhMYWE2b3J6SUpRZEg2d2JPT056aDAvTHEzMUNlZ3gycUVDMWlnR3VmOHErUGFUQQpUTHVMTTNRQnpsWjA5SkY5ZllWM2ZEVWdWWGxUd3BGcXQrSklMbFNiZEFrdDJXdzFyT0lRREgvdUhVdGJqN1duCmZzR0s3S2kwTm5CeFJncU8yS1BtV0QzNDRteUIwKzk3QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVVlZ1R01QdnUrQWZJNStOMjdUYU1xM3dWeldrd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBS1R4citVRFpFWDhVWitSRUJJbHh1OWJ6Zk9NSGdpZ0ZFM2NHS25zeDMvdzNSTHBtOWhXT0hGRVJvUWYKWHcxZzY5Z3hRbDFqUGs2K0RYVFVGcVRENVVyN1hpMEZiRUJBMGp0TE1RcW8wdGdDTXdQYXZnWVRKd2xOQmEvcgpXNWFKTThKNmh4a2NaL2liNUVXTXFkMGNJSlVmS3RDc0x0ZXR3UmpEMGQzdzlJUlgvc3N4WkcreW9acy8wVS8vCjc5dVJZOEdmbmZqWEp0RHV5MHNVK1N4SkhkeHhQYVJ2ZEJDc05mZFArblpsd0dDNUpoZDNKaFJtc29nQkt1SUYKaWtaZno3QmQyVG9oNWlLdDhoZXRMTjhOOXlnSU95Tk5XYWNKbDhTYUI2d1lFeXVXbGtHd0dWc0l4elM5d1p1Ugo3dzF5b0QyTDRwRmFpKzJCZmJlQTZvamdBUnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /validate-elbv2-k8s-aws-v1beta1-ingressclassparams
    failurePolicy: Fail
    name: vingressclassparams.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingressclassparams
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQVA4NlhwUjdEeFpNVnBPbUF1b204d0l3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TURNeE1ETTJNRFZhRncwek5qQXlNamt4TURNMk1EVmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURCenpjL0FXeXRic3hXSGR1empjc2F6RlV5c1dJcEFIWjNLL0JGMEd5ZiszTnVwT2w1My94cAphRXhUZGdPUE55cjg3TGNSZlZESlhNdUZ1cGtQTHVyZnBPUGFHMk9WYVFSNi8rREg3eVlkQ0ZaeUpzNTdqdjVXClhpRTA3cDNueEJ4R0tZNm9QR0xqTVBDMmhIRXFJN2FCZXd2SXBpeENlZGM4VUlFZHdnTllJaGJqemJkZHRQdmsKSnpGZ3lwR3Z6NFpxcVVaTmhMYWE2b3J6SUpRZEg2d2JPT056aDAvTHEzMUNlZ3gycUVDMWlnR3VmOHErUGFUQQpUTHVMTTNRQnpsWjA5SkY5ZllWM2ZEVWdWWGxUd3BGcXQrSklMbFNiZEFrdDJXdzFyT0lRREgvdUhVdGJqN1duCmZzR0s3S2kwTm5CeFJncU8yS1BtV0QzNDRteUIwKzk3QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVVlZ1R01QdnUrQWZJNStOMjdUYU1xM3dWeldrd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBS1R4citVRFpFWDhVWitSRUJJbHh1OWJ6Zk9NSGdpZ0ZFM2NHS25zeDMvdzNSTHBtOWhXT0hGRVJvUWYKWHcxZzY5Z3hRbDFqUGs2K0RYVFVGcVRENVVyN1hpMEZiRUJBMGp0TE1RcW8wdGdDTXdQYXZnWVRKd2xOQmEvcgpXNWFKTThKNmh4a2NaL2liNUVXTXFkMGNJSlVmS3RDc0x0ZXR3UmpEMGQzdzlJUlgvc3N4WkcreW9acy8wVS8vCjc5dVJZOEdmbmZqWEp0RHV5MHNVK1N4SkhkeHhQYVJ2ZEJDc05mZFArblpsd0dDNUpoZDNKaFJtc29nQkt1SUYKaWtaZno3QmQyVG9oNWlLdDhoZXRMTjhOOXlnSU95Tk5XYWNKbDhTYUI2d1lFeXVXbGtHd0dWc0l4elM5d1p1Ugo3dzF5b0QyTDRwRmFpKzJCZmJlQTZvamdBUnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: vtargetgroupbinding.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQVA4NlhwUjdEeFpNVnBPbUF1b204d0l3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TURNeE1ETTJNRFZhRncwek5qQXlNamt4TURNMk1EVmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURCenpjL0FXeXRic3hXSGR1empjc2F6RlV5c1dJcEFIWjNLL0JGMEd5ZiszTnVwT2w1My94cAphRXhUZGdPUE55cjg3TGNSZlZESlhNdUZ1cGtQTHVyZnBPUGFHMk9WYVFSNi8rREg3eVlkQ0ZaeUpzNTdqdjVXClhpRTA3cDNueEJ4R0tZNm9QR0xqTVBDMmhIRXFJN2FCZXd2SXBpeENlZGM4VUlFZHdnTllJaGJqemJkZHRQdmsKSnpGZ3lwR3Z6NFpxcVVaTmhMYWE2b3J6SUpRZEg2d2JPT056aDAvTHEzMUNlZ3gycUVDMWlnR3VmOHErUGFUQQpUTHVMTTNRQnpsWjA5SkY5ZllWM2ZEVWdWWGxUd3BGcXQrSklMbFNiZEFrdDJXdzFyT0lRREgvdUhVdGJqN1duCmZzR0s3S2kwTm5CeFJncU8yS1BtV0QzNDRteUIwKzk3QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVVlZ1R01QdnUrQWZJNStOMjdUYU1xM3dWeldrd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBS1R4citVRFpFWDhVWitSRUJJbHh1OWJ6Zk9NSGdpZ0ZFM2NHS25zeDMvdzNSTHBtOWhXT0hGRVJvUWYKWHcxZzY5Z3hRbDFqUGs2K0RYVFVGcVRENVVyN1hpMEZiRUJBMGp0TE1RcW8wdGdDTXdQYXZnWVRKd2xOQmEvcgpXNWFKTThKNmh4a2NaL2liNUVXTXFkMGNJSlVmS3RDc0x0ZXR3UmpEMGQzdzlJUlgvc3N4WkcreW9acy8wVS8vCjc5dVJZOEdmbmZqWEp0RHV5MHNVK1N4SkhkeHhQYVJ2ZEJDc05mZFArblpsd0dDNUpoZDNKaFJtc29nQkt1SUYKaWtaZno3QmQyVG9oNWlLdDhoZXRMTjhOOXlnSU95Tk5XYWNKbDhTYUI2d1lFeXVXbGtHd0dWc0l4elM5d1p1Ugo3dzF5b0QyTDRwRmFpKzJCZmJlQTZvamdBUnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: aws-lb-controller
        path: /validate-networking-v1-ingress
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: vingress.elbv2.k8s.aws
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
    sideEffects: None
