apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flink-operator-repo
  namespace: flink
spec:
  interval: 1h0m0s
  url: https://downloads.apache.org/flink/flink-kubernetes-operator-1.15.0/
