name: Branch Reconciliation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  
jobs:
  reconciliate-branch:
    strategy:
      matrix:
        target_branch: ["qa", "staging"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge main -> ${{ matrix.target_branch }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: ${{ matrix.target_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify
        if: failure()
        uses: dfds/shared-workflows/.github/actions/automation-slack-notifier@master
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_message: 'Could not merge main into ${{ matrix.target_branch }}. Please check the logs.'
