apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-sso
  namespace: argocd
spec:
  refreshInterval: "60m"
  secretStoreRef:
    name: vault-argo
    kind: SecretStore
  target:
    name: argo-sso
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: oidc.clientSecret
      remoteRef:
        key: argo
        property: clientSecret