---
# Source: kube-state-metrics/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: flux-kube-state-metrics
    app.kubernetes.io/name: flux-kube-state-metrics
    app.kubernetes.io/instance: flux-kube-state-metrics
  name: flux-kube-state-metrics
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["list", "watch"]
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kustomize.toolkit.fluxcd.io
      - helm.toolkit.fluxcd.io
      - notification.toolkit.fluxcd.io
      - image.toolkit.fluxcd.io
    resources:
      - gitrepositories
      - buckets
      - helmrepositories
      - helmcharts
      - ocirepositories
      - kustomizations
      - helmreleases
      - alerts
      - providers
      - receivers
      - imagerepositories
      - imagepolicies
      - imageupdateautomations
    verbs:
      - list
      - watch
