---
# Source: kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: flux-kube-state-metrics
    app.kubernetes.io/name: flux-kube-state-metrics
    app.kubernetes.io/instance: flux-kube-state-metrics
  name: flux-kube-state-metrics
  namespace: flux-system
